[package]
name = "transact"
version = "0.1.0"
authors = ["Bitwise IO, Inc."]
edition = "2018"

[dependencies]
hex = "0.3"
protobuf = "2"
rand = "0.6"
sha2 = "0.8"
lmdb-zero = ">=0.4.1"
log = { version = "0.4", features = ["std"] }
cbor-codec = "0.7"
libc = ">=0.2.35"
openssl = "0.10"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
sawtooth-sdk = "0.1"
rand_hc = "0.1"

[build-dependencies]
protoc-rust = "2"

[features]
nightly = []
